AllCops:
  Exclude:
    - 'okuribito.gemspec'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

LineLength:
  Max: 100
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
